/*****************************************************************************/
/*         (c) Copyright, Real-Time Innovations, All rights reserved.        */
/*                                                                           */
/*         Permission to modify and use for internal purposes granted.       */
/* This software is provided "as is", without warranty, express or implied.  */
/*                                                                           */
/*****************************************************************************/

module rti {
	module example {

		struct ShapeType {
			@key // identifies the instance (a.k.a data-object)
			string<128> color; 
          
			long x;
			long y;
			long shapesize; 
		};

        enum ShapeFillKind {
            SOLID_FILL,
            TRANSPARENT_FILL,
            HORIZONTAL_HATCH_FILL,
            VERTICAL_HATCH_FILL
        };

        struct ShapeTypeExtended : ShapeType {
            ShapeFillKind fillKind;
            float angle;
        };



        const short PICTURE_WIDTH  = 640;
        const short PICTURE_HEIGHT = 480; 
        struct PictureType {
            short dim;                         // dimension: width or height
            sequence<octet, PICTURE_WIDTH * PICTURE_HEIGHT> pixel; // pixels
        };

        struct PictureShapeType: ShapeTypeExtended {
            PictureType picture;
        };
	};
};