/*****************************************************************************/
/*         (c) Copyright, Real-Time Innovations, All rights reserved.        */
/*                                                                           */
/*         Permission to modify and use for internal purposes granted.       */
/* This software is provided "as is", without warranty, express or implied.  */
/*                                                                           */
/*****************************************************************************/

module rti {

    module picture {
        const short WIDTH  = 640;
        const short HEIGHT = 480; 

        @nested 
        struct PictureType {
            short dim;                             // dimension: width or height
            sequence<octet, WIDTH * HEIGHT> pixel; // pixels
        }; 
    };

	module shapes {

		struct ShapeType {
			@key // identifies the instance (a.k.a data-object)
			string<128> color; 
          
			long x;
			long y;
			long shapesize; 
		};

        enum ShapeFillKind {
            SOLID_FILL,
            TRANSPARENT_FILL,
            HORIZONTAL_HATCH_FILL,
            VERTICAL_HATCH_FILL
        };

        struct ShapeTypeExtended : ShapeType {
            ShapeFillKind fillKind;
            float angle;
        };


        struct PictureShapeType : ShapeTypeExtended {
            picture::PictureType picture;
        };


        module name { // Names defined the DDS-XML file
            const string SHAPES_PUB_IF    = "ShapesIfLib::Shapes_Pub";
            const string SHAPES_SUB_IF    = "ShapesIfLib::Shapes_Sub";
            const string SHAPE_TYPE       = "ShapeType";
            const string SHAPE_WRITER     = "_pub::Shape_writer";
            const string SHAPE_READER     = "_sub::Shape_reader";
        };
	};
};